Link fix
pepedropo1/Portfolio pull request #3
Opened 2021-11-25 11:45 UTC by pepedropo1

Added a lot of code:
-Link fixed;
- Added work section of my projects;
- Styled the page.

2021-11-25 20:17 UTC, keneogu requested changes
Hi @pepedropo1 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that breaks the following general requirement:

##- Pull request should have a descriptive title explaining what changes are inside.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

2021-11-25 22:32 UTC, DammyShittu requested changes
Hi @pepedropo1 , 

I really commend all the efforts that you have put into this milestone. **YOU ROCK 🥇**

However, there are some issues that you still need to work on to go to the next project but you are ALMOST THERE!

# REQUIRED CHANGES ♻️

_Check the comments under the review._

# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 22:32 UTC, DammyShittu commented on styles.css
>    color: #fff;
- [ ] Kindly add the appropriate color for the hover interaction of the button.
For ease, the background-color on hover is `#36B37F` 👍

2021-11-25 22:32 UTC, DammyShittu commented on styles.css
>    text-align: center;
- [ ] Kindly add the appropriate color for the active interaction of the button.
For ease, the background-color on hover is `#008552` 👍

2021-11-25 22:32 UTC, DammyShittu commented on styles.css
> +  }
- [ ] Regarding the information that you requested help for, I would advise you to remove these declarations from the class above `display: flex;
    justify-content: space-evenly;`. and add the information in the next comment 👇

2021-11-25 22:32 UTC, DammyShittu commented on styles.css
> +    flex-wrap: wrap;
- [ ] In continuation of the above comment, you  can also remove ` flex-wrap: wrap;`, increase  the `width` and add `display: inline-block;` I hope this helps 😃

2021-11-25 22:32 UTC, DammyShittu commented on index.html
> +          <div class="grid-container">
- [ ] It would be nice to wrap the entire `About Me` section in a `section` tag instead of a `div` tag. This will make the code look more semantic and also follow the project requirement. 😃

2021-11-26 08:21 UTC, pepedropo1 commented on styles.css
> +    flex-wrap: wrap;
Hi thank you for your comments, but is it not a requirement to use flexbox?

2021-11-26 09:40 UTC, DammyShittu commented on styles.css
> +    flex-wrap: wrap;
Hello @pepedropo1,

I believe the requirement says you need to align the content of the technology categories section with Flexbox, and you have done that with the `nest-flex` class. 😉

2021-11-26 11:01 UTC, lily-coder requested changes
Hi @pepedropo1 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![image](https://user-images.githubusercontent.com/63964646/143570923-cabe60e6-a06f-4ef8-a254-ae50a374f7de.png)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 11:01 UTC, lily-coder commented on index.html
> +          <section class="grid-container">
- [ ] [REQUIRED] Please ensure the About me section has the proper background image as in the project requirements. Your About me section is lacking the background images.
- **FIGMA TEMPLATE**
![Screenshot](https://user-images.githubusercontent.com/63964646/143569637-b76253f6-4672-4eef-aa56-40efd3edbceb.PNG)
- **YOUR DESIGN**
![Aboutme](https://user-images.githubusercontent.com/63964646/143570142-6b65e75a-6bd0-4d29-9aeb-06809ae16ce4.PNG)
![20211126_133953](https://user-images.githubusercontent.com/63964646/143570361-8006c245-7aa7-4534-b4cf-95836f7d5013.jpg)

2021-11-26 12:59 UTC, lily-coder approved these changes
Hi @pepedropo1 , 

Good work implementing the changes as requested by the previous reviewers. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/63964646/143584526-83dcebc8-c9b9-43de-94e9-b0b8fbb6c15b.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 13:24 UTC, merged